name: tests
on:
  push:
  pull_request:
    branches:
      # only branches from forks which have the form 'user:branch-name'
      - '**:**'
jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.9, "3.10"]
        flags: ["-v --full -n 2", "-v -n 1"]
        include:
          - os: macos-latest
            python: "3.10"
            flags: "-v -n 2"
          - os: windows-latest
            python: "3.10"
            flags: "-v -n 2"
    runs-on: ${{ matrix.os }}
    env:
      flags: ${{ matrix.flags }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          environment-file: .github/test_conda_env.yml
      - name: print conda environment info
        run: |
          conda info -a
          conda list
      - name: install package
        run: |
          pip install -v --no-deps .
      - name: run test suite
        run: |
          mkdir empty; cd empty; cp ../.coveragerc ./
          coverage run -m yam.tests $flags
          coverage combine
          coverage xml -o ../coverage.xml
      - name: upload coverage
        uses: codecov/codecov-action@v3
