name: tests
on:
  push:
  pull_request:
    branches:
      # only branches from forks which have the form 'user:branch-name'
      - '**:**'
jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.6, 3.7, 3.8, 3.9, "3.10"]
        flags: ["-v -n 2"]
        fftw: [no]
        include:
          - os: macos-latest
            python: "3.10"
            flags: "-v -n 2"
            fftw: no
          - os: windows-latest
            python: "3.10"
            flags: "-v -n 2"
            fftw: no
          - os: ubuntu-latest
            python: "3.10"
            flags: "-v -n 0"
            fftw: no
          - os: ubuntu-latest
            python: "3.10"
            flags: "-v --full n 2"
            fftw: no
          - os: ubuntu-latest
            python: "3.10"
            flags: "-v -n 2"
            fftw: yes

    runs-on: ${{ matrix.os }}
    env:
      FLAGS: ${{ matrix.flags }}
      YAM_FFTW: ${{ matrix.fftw }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          environment-file: .github/test_conda_env${{ (matrix.fftw == 'yes') && '_pyfftw' || '' }}.yml
      - name: print conda environment info
        run: |
          conda info -a
          conda list
      - name: install package
        run: |
          pip install -v --no-deps .
      - name: run test suite
        run: |
          mkdir empty; cd empty; cp ../.coveragerc ./
          coverage run -m yam.tests $FLAGS
          coverage combine
          coverage xml -o ../coverage.xml
      - name: upload coverage
        uses: codecov/codecov-action@v3
